### ISSUE TITLE
decode panic

### ISSUE THREAD

**Issue by Hanson** [makiuchi-d/gozxing#52]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0xbf0648]

goroutine 1 [running]:
github.com/makiuchi-d/gozxing.NewLuminanceSourceFromImage({0x0, 0x0})
	D:/Program Files/GOPATH/pkg/mod/github.com/makiuchi-d/gozxing@v0.1.1/go_image_luminance_source.go:19 +0x28
github.com/makiuchi-d/gozxing.NewBinaryBitmapFromImage({0x0?, 0x0?})
	D:/Program Files/GOPATH/pkg/mod/github.com/makiuchi-d/gozxing@v0.1.1/go_image_luminance_source.go:10 +0x27
```

here is my code 
```
func main() {
	// open and decode image file
	file, _ := os.Open("D:\\AppData\\Local\\Temp\\123.jpg")
	img, _, _ := image.Decode(file)

	// prepare BinaryBitmap
	bmp, _ := gozxing.NewBinaryBitmapFromImage(img)

	// decode image
	qrReader := qrcode.NewQRCodeReader()
	result, _ := qrReader.Decode(bmp, nil)

	fmt.Println(result)
}
```

**Comment by makiuchi-d** [comment]
Please check errors from `os.Open` and/or `image.Decode`.
And share the file that causes this problem.

**Comment by Hanson** [comment]
![1670837461](https://user-images.githubusercontent.com/10583423/208619478-2e702111-3772-4888-b950-0e3a86205141.png)
@makiuchi-d the qrcode just like this.

**Comment by makiuchi-d** [comment]
I got a result: `https://c.weixin.com/g/fOXme-Gt6iXGZSvd`
**Please check errors from `os.Open` and/or `image/Decode`.**
